[packages.apt]
to_remove = []
[packages.apt.base]
packages = [
  "build-essential",
  "pkg-config",
  "libssl-dev",
  "cmake",
  "ca-certificates",
  "wl-clipboard",
]
[packages.apt.extra]
packages = ["jq"]
