[tools]
go = "latest"
node = "24.14.0"
rust = "latest"
python = "latest"
uv = "latest"
starship = "latest"
eza = "latest"
bat = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
ripgrep = "latest"
lazygit = "latest"
shellcheck = "latest"
github-cli = "latest"
