[tools]
go = "latest"
node = "lts"
python = "latest"
rust = "latest"

fzf = "latest"
ghq = "latest"
lazygit = "latest"

bat = "latest"
fd = "latest"
eza = "latest"
ripgrep = "latest"
starship = "latest"
uv = "latest"

github-cli = "latest"

bats = "latest"
shellcheck = "latest"
shfmt = "latest"
